

// <article class="products__product--item">
// <figure class="products__product--img">
// <img src="img/prod-2.webp" alt="">
// </figure>
//    <div class="products__product--info">
//     <h3>African Continet <span>14K Gold</span></h3>
//     <span class="products__product--sex">
//       3 colors / unisex
//     </span>
//     <h2 class="products__product--price">
//        $31,500
//     </h2>
//    </div>
//    <figcaption class="products__product--overlay">
//       <button>
//        <svg>
//         <use xlink:href="img/sprite.svg#icon-search1"></use>
//        </svg>
//       </button>
//      <button>
//       <svg>
//         <use xlink:href="img/sprite.svg#icon-shopping-bag"></use>
//        </svg>
//      </button>
//    </figcaption>
// </article>



const products = [
  {
    id: "1",
    img: "./img/prod-1.webp",
    name: "african pendant",
    desc: "african continet",
    karat: "14kpt",
    colors: "2 tone colors",
    gender: "unisex",
    made: "2022",
    price: 31.500,
    page: "./img/sprite.svg#icon-search1",
    toCart: "./img/sprite.svg#icon-shopping-bag",
    category: "pendant",
  },
  {
    id: "2",
    img: "./img/prod-2.webp",
    name: "tennis necklace",
    desc: "eternity round bezel set necklace",
    karat: "2.66ctw",
    colors: "1 color silver",
    gender: "female",
    made: "2021",
    price: 5.646,
    category: "necklace",
  },
  {
    id: "3",
    img: "./img/prod-3.webp",
    name: "cuban chain choker",
    desc: "24mm miami cuban link necklace",
    karat: "14k 71.b7ctw",
    colors: "3 color silver",
    gender: "male",
    made: "2018",
    price: 9.40,
    category: "necklace",
  },
  {
    id: "4",
    img: "./img/prod-4.webp",
    name: "cross pendant",
    desc: "filigree bezel cross pendant",
    karat: "14k",
    colors: "3 color silver",
    gender: "unisex",
    made: "2021",
    price: 3.750,
    category: "pendant",
  },
  {
    id: "5",
    img: "./img/prod-5.webp",
    name: "leaf pendant",
    desc: "large two layer cannabis leaf pendant",
    karat: "14k",
    colors: "3 color 2 tone",
    gender: "male",
    made: "2020",
    price: 18.523,
    category: "pendant",
  },
  {
    id: "6",
    img: "./img/prod-6.webp",
    name: "cross ring",
    desc: "bordered point cross ring",
    karat: "14k",
    colors: "3 color silver",
    gender: "female",
    made: "2018",
    price: 3.334,
    category: "ring",
  },
  {
    id: "7",
    img: "./img/prod-7.webp",
    name: "jesus pendant",
    desc: "christ the redeemer pendant",
    karat: "14k",
    colors: "3 color",
    gender: "male",
    made: "2022",
    price: 5.925,
    category: "pendant",
  },
  {
    id: "8",
    img: "./img/prod-8.webp",
    name: "square ice ring",
    desc: "square tulip cluster ring",
    karat: "14k",
    colors: "3 color silver",
    gender: "female",
    made: "2022",
    price: 4.225,
    category: "ring",
  },
  {
    id: "9",
    img: "./img/prod-9.webp",
    name: "engagement ring",
    desc: "round double halo twist ring",
    karat: "14k",
    colors: "3 color silver",
    gender: "female",
    made: "2022",
    price: 2.188,
    category: "ring",
  },
  {
    id: "10",
    img: "./img/prod-10.webp",
    name: "link bracelet cuban",
    desc: "flat byzantine link bracelet ",
    karat: "14k 11ctw",
    colors: "3 color silver",
    gender: "male",
    made: "2023",
    price: 52.34, 
   category: "bracelet",
  },
  {
    id: "11",
    img: "./img/prod-11.webp",
    name: "cuban ice bracelet",
    desc: "22mm miami cuban link bracelet",
    karat: "14k 22.20ctw",
    colors: "3 color silver",
    gender: "unisex",
    made: "2022",
    price: 5.545,
    category: "bracelet",
  },
  {
    id: "12",
    img: "./img/prod-12.webp",
    name: "rolex watch",
    desc: "rolex datajust 18k/steel 26mm",
    karat: "0.87ctw (69173)",
    colors: "3 color silver",
    gender: "female",
    made: "2018",
    price: 7.752,
    category: "watch",
  },
  {
    id: "13",
    img: "./img/prod-13.webp",
    name: "rolex watch",
    desc: "rolex datejust 31mm steel",
    karat: "(178240)",
    colors: "1 color ",
    gender: "female",
    made: "2022",
    price:44.33,
   category: "watch",
  },
  {
    id: "14",
    img: "./img/prod-14.webp",
    name: "rolex watch",
    desc: "audemars piguet royal 0ak 41mm steel",
    karat: "14k",
    colors: "3 color silver",
    gender: "male",
    made: "2022",
    price: 9.403,
    category: "watch",
  },
  {
    id: "15",
    img: "./img/prod-15.webp",
    name: "rolex watch",
    desc: "rolex date just 36mm steel/",
    karat: "18K (16233)",
    colors: "3 color silver",
    gender: "male",
    made: "2022",
    price: 95.456,
    category: "watch",
  },
  {
    id: "16",
    img: "./img/prod-16.webp",
    name: "cross ring",
    desc: "bordered point cross ring",
    karat: "14k",
    colors: "3 color silver",
    gender: "female",
    made: "2018",
    price: 55.44,
    category: "earing",
  },
  {
    id: "17",
    img: "./img/prod-17.webp",
    name: "customize",
    desc: "customized",
    karat: "14k",
    colors: "3 color silver",
    gender: "female",
    made: "2018",
    price: 70.45,
    category: "custom",
  },
  {
    id: "18",
    img: "./img/prod-18.webp",
    name: "jesus head pendant",
    desc: "jesus pendant",
    karat: "14k",
    colors: "3 color silver",
    gender: "unisex",
    made: "2018",
    price: 55.33, 
    category: "pendant",
  },
  {
    id: "19",
    img: "./img/prod-19.webp",
    name: "cuban",
    desc: "cuban link chain",
    karat: "14k",
    colors: "3 color silver",
    gender: "male",
    made: "2018",
    price: 2.488,
    category: "necklace",
  },
  {
    id: "20",
    img: "./img/prod-20.webp",
    name: "jesus head pendant",
    desc: "jesus tears pendant",
    karat: "14k",
    colors: "3 color silver",
    gender: "male",
    made: "2021",
    price: 1.563,
    category: "pendant",
  },
  {
    id: "21",
    img: "./img/prod-21.webp",
    name: "jesus head pendant",
    desc: "jesus pendant",
    karat: "14k",
    colors: "3 color silver",
    gender: "unisex",
    made: "2018",
    price: 8.900,
    category: "pendant",
  },
  {
    id: "22",
    img: "./img/prod-22.webp",
    name: "jesus pendant",
    desc: "jesus pendant",
    karat: "14k",
    colors: "3 color silver",
    gender: "male",
    made: "2022",
    price: 5.933,
    category: "pendant",
  },
  {
    id: "24",
    img: "./img/prod-24.webp",
    name: "cross pendant",
    desc: "jesus crucifix pendant",
    karat: "14k",
    colors: "3 color",
    gender: "male",
    made: "2021",
    price: 4.570,
    category: "pendant",
  },
  {
    id: "25",
    img: "./img/prod-25.webp",
    name: "mini earring",
    desc: "mini evil earrings",
    karat: "14k",
    colors: "3 color",
    gender: "unisex",
    made: "2023",
    price: 9.83,
    category: "earing",
  },
  {
    id: "26",
    img: "./img/enga-1.webp",
    name: "engagement ring",
    desc: "iced out solo bach ring",
    karat: "14k",
    colors: "3 color",
    gender: "female",
    made: "2023",
    price: 3.823,
    category: "ring",
  },
]
  
  products.sort(() => (Math.random() > .5) ? 1 : -1);

